export const pricingPlans = [
  {
    name: "Free Tier",
    price: "0",
    period: "/month",
    description: "Perfect for getting started",
    features: [
      "Up to 100 tickets per month",
      "Basic ticket summaries",
      "Standard categorization",
      "Simple QA analysis",
      "Email support",
      "Basic analytics dashboard",
    ],
    highlighted: false,
    buttonText: "Get Started",
    link: "https://ai-ticket.vercel.app/dashboard",
    callout: "Get started for free • No credit card required",
    buttonVariant: "outline",
  },
  {
    name: "Pro Plan",
    price: "49",
    period: "/month",
    description: "For growing teams",
    features: [
      "Unlimited ticket processing",
      "Advanced AI customization",
      "Full historical data access",
      "Enhanced insights & reporting",
      "Priority support",
      "Custom integration options",
      "Advanced analytics",
      "API access",
    ],
    highlighted: true,
    buttonText: "Start Free Trial",
    link: "https://buy.stripe.com/test_cN2g1p6AE2wxbXa003",
    priceId: "price_1QuYSoBgH7v91aCMS6vmBUU6",
    callout: "Pay monthly, cancel anytime",
    buttonVariant: "default",
  },
  {
    name: "Free Tier",
    price: "0",
    period: "/year",
    description: "Perfect for getting started",
    features: [
      "Up to 1200 tickets per year",
      "Basic ticket summaries",
      "Standard categorization",
      "Simple QA analysis",
      "Email support",
      "Basic analytics dashboard",
    ],
    highlighted: false,
    buttonText: "Get Started",
    link: "https://ai-ticket.vercel.app/dashboard",
    callout: "Get started for free • No credit card required",
    buttonVariant: "outline",
  },
  {
    name: "Pro Plan",
    price: "499",
    period: "/year",
    description: "For growing teams",
    features: [
      "Unlimited ticket processing",
      "Advanced AI customization",
      "Full historical data access",
      "Enhanced insights & reporting",
      "Priority support",
      "Custom integration options",
      "Advanced analytics",
      "API access",
    ],
    highlighted: true,
    buttonText: "Start Free Trial",
    link: "https://buy.stripe.com/test_00gdTh0cgdbb4uI9AC",
    priceId: "price_1QuYaXBgH7v91aCMgrCZxibY",
    callout: "Save $89 yearly",
    buttonVariant: "default",
  },
];
